local w=require 'wezterm'
local wezterm= w
return {
	color_scheme = 'AyuDark (Gogh)', --OneDark (base16),
	font = w.font('JetBrainsMono NF',{weight = 'Regular',italic = false}),
	font_size = 18.00,
	default_prog = {'C:\\Program Files\\PowerShell\\7\\pwsh.exe','-l'},
	default_cwd = 'D:\\',
	enable_tab_bar = true,
	tab_bar_at_bottom = true,
	hide_tab_bar_if_only_one_tab = true,
  colors = {
    tab_bar = {
      background = '#0b0022',
      active_tab = {
        bg_color = '#101010',
        fg_color = '#c0c0c0',
        intensity = 'Bold',
        underline = 'Single',
        italic = false,
        strikethrough = false,
      },
      inactive_tab = {
        bg_color = '#222222',
        fg_color = '#808080',
      },
      inactive_tab_hover = {
        bg_color = '#101010',
        fg_color = '#909090',
        italic = true,
      },
      new_tab = {
        bg_color = '#101010',
        fg_color = '#808080',
      },
      new_tab_hover = {
        bg_color = '#101010',
        fg_color = '#909090',
        italic = true,
      },
    },
  },
	window_background_opacity = 1.0,
  text_background_opacity = 1.0,
	leader = { key="o", mods="CTRL" },
--  disable_default_key_bindings = true,
	keys = {
        { key = "a", mods = "LEADER|CTRL",  action=wezterm.action{SendString="\x01"}},
        { key = "-", mods = "LEADER",       action=wezterm.action{SplitVertical={domain="CurrentPaneDomain"}}},
        { key = ".",mods = "LEADER",       action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
        { key = "z", mods = "LEADER",       action="TogglePaneZoomState" },
        { key = "c", mods = "LEADER",       action=wezterm.action{SpawnTab="CurrentPaneDomain"}},
        { key = "h", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Left"}},
        { key = "j", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Down"}},
        { key = "k", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Up"}},
        { key = "l", mods = "LEADER",       action=wezterm.action{ActivatePaneDirection="Right"}},
        { key = "H", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Left", 5}}},
        { key = "J", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Down", 5}}},
        { key = "K", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Up", 5}}},
        { key = "L", mods = "LEADER|SHIFT", action=wezterm.action{AdjustPaneSize={"Right", 5}}},
        { key = "1", mods = "LEADER",       action=wezterm.action{ActivateTab=0}},
        { key = "2", mods = "LEADER",       action=wezterm.action{ActivateTab=1}},
        { key = "3", mods = "LEADER",       action=wezterm.action{ActivateTab=2}},
        { key = "4", mods = "LEADER",       action=wezterm.action{ActivateTab=3}},
        { key = "5", mods = "LEADER",       action=wezterm.action{ActivateTab=4}},
        { key = "6", mods = "LEADER",       action=wezterm.action{ActivateTab=5}},
        { key = "7", mods = "LEADER",       action=wezterm.action{ActivateTab=6}},
        { key = "8", mods = "LEADER",       action=wezterm.action{ActivateTab=7}},
        { key = "9", mods = "LEADER",       action=wezterm.action{ActivateTab=8}},
        { key = "&", mods = "LEADER|SHIFT", action=wezterm.action{CloseCurrentTab={confirm=true}}},
        { key = "x", mods = "LEADER",       action=wezterm.action{CloseCurrentPane={confirm=true}}},

        { key = "n", mods="SHIFT|CTRL",     action="ToggleFullScreen" },
        { key="v",   mods="CTRL",     action="Paste"},
        { key="y",   mods="CTRL",     action="Copy"},
    },}
